name: Test TensorLy-Torch

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        echo "* Updating pip"
        python -m pip install --upgrade pip
        echo "* Installing requirements"
        python -m pip install -r requirements.txt
        echo "* Installing documentation requirements"
        python -m pip install -r doc/requirements_doc.txt
        echo "* Installing PyTorch"
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    - name: Install TensorLy dev
      run: |
        CWD=`pwd`
        echo 'Cloning TensorLy in ${CWD}'
        mkdir git_repos
        cd git_repos
        git clone https://github.com/tensorly/tensorly
        cd tensorly
        python -m pip install -e .
        cd ..    
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest -vvv tltorch
